import type { ActionDefinition } from './types';

/**
 * Catálogo canónico de acciones (IDs en inglés jerárquicos).
 * aliases: IDs legacy en español para menús / store existentes.
 */
export const ACTION_CATALOG: readonly ActionDefinition[] = [
  // Transport
  {
    id: 'transport.togglePlay',
    name: 'Reproducir / Pausar',
    description: 'Alterna reproducción y pausa',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.toggle',
    aliases: ['transporte.reproducir'],
    defaultShortcuts: ['Space'],
  },
  {
    id: 'transport.pause',
    name: 'Pausar',
    description: 'Pausa la reproducción',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.toggle',
    defaultShortcuts: ['Enter'],
  },
  {
    id: 'transport.stop',
    name: 'Detener',
    description: 'Detiene el transporte',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.stop',
    aliases: ['transporte.detener'],
    defaultShortcuts: ['Ctrl+Space'],
  },
  {
    id: 'transport.record',
    name: 'Grabar',
    description: 'Alterna grabación',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.toggleRecord',
    aliases: ['transporte.grabar'],
    defaultShortcuts: ['Ctrl+R'],
  },
  {
    id: 'transport.toggleLoop',
    name: 'Activar / desactivar bucle',
    description: 'Alterna el modo loop',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.toggleLoop',
    aliases: ['transporte.loop', 'ui.toggleLoop'],
    defaultShortcuts: ['R'],
  },
  {
    id: 'transport.goToStart',
    name: 'Ir al inicio',
    description: 'Mueve el playhead al inicio del proyecto',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.seek',
    aliases: ['transporte.inicio'],
    defaultShortcuts: ['W', 'Home'],
  },
  {
    id: 'transport.goToEnd',
    name: 'Ir al final',
    description: 'Mueve el playhead al final',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    aliases: ['transporte.fin'],
    defaultShortcuts: ['End'],
  },
  {
    id: 'transport.toggleMetronome',
    name: 'Metrónomo',
    description: 'Activa o desactiva el metrónomo',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.toggleMetronome',
    aliases: ['transporte.metronomo', 'ui.toggleMetronomo'],
    defaultShortcuts: ['K'],
  },
  {
    id: 'transport.stepBack',
    name: 'Retroceder playhead',
    description: 'Retrocede el playhead',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.back',
    aliases: ['transporte.playheadAnterior', 'transporte.rebobinar'],
    defaultShortcuts: ['ArrowLeft'],
  },
  {
    id: 'transport.stepForward',
    name: 'Avanzar playhead',
    description: 'Avanza el playhead',
    category: 'Transport',
    context: 'global',
    risk: 'write',
    commandType: 'transport.forward',
    aliases: ['transporte.playheadSiguiente', 'transporte.avanceRapido'],
    defaultShortcuts: ['ArrowRight'],
  },

  // Project
  {
    id: 'project.new',
    name: 'Nuevo proyecto',
    description: 'Crea un proyecto nuevo',
    category: 'Project',
    context: 'global',
    risk: 'dangerous',
    aliases: ['proyecto.nuevo'],
    defaultShortcuts: ['Ctrl+N'],
  },
  {
    id: 'project.open',
    name: 'Abrir proyecto',
    description: 'Abre un proyecto existente',
    category: 'Project',
    context: 'global',
    risk: 'dangerous',
    aliases: ['proyecto.abrir'],
    defaultShortcuts: ['Ctrl+O'],
  },
  {
    id: 'project.save',
    name: 'Guardar',
    description: 'Guarda el proyecto',
    category: 'Project',
    context: 'global',
    risk: 'write',
    aliases: ['proyecto.guardar'],
    defaultShortcuts: ['Ctrl+S'],
  },
  {
    id: 'project.saveAs',
    name: 'Guardar como',
    description: 'Guarda el proyecto con otro nombre',
    category: 'Project',
    context: 'global',
    risk: 'write',
    aliases: ['proyecto.guardarComo'],
    defaultShortcuts: ['Ctrl+Shift+S'],
  },
  {
    id: 'project.close',
    name: 'Cerrar proyecto',
    description: 'Cierra el proyecto actual',
    category: 'Project',
    context: 'global',
    risk: 'dangerous',
    aliases: ['proyecto.cerrar'],
    defaultShortcuts: ['Ctrl+F4'],
  },

  // Editing
  {
    id: 'editing.undo',
    name: 'Deshacer',
    description: 'Deshace la última operación',
    category: 'Editing',
    context: 'global',
    risk: 'write',
    aliases: ['edicion.deshacer'],
    defaultShortcuts: ['Ctrl+Z'],
  },
  {
    id: 'editing.redo',
    name: 'Rehacer',
    description: 'Rehace la última operación deshecha',
    category: 'Editing',
    context: 'global',
    risk: 'write',
    aliases: ['edicion.rehacer'],
    defaultShortcuts: ['Ctrl+Shift+Z', 'Ctrl+Y'],
  },
  {
    id: 'editing.cut',
    name: 'Cortar',
    description: 'Corta la selección al portapapeles',
    category: 'Editing',
    context: 'global',
    risk: 'write',
    aliases: ['edicion.cortar'],
    defaultShortcuts: ['Ctrl+X'],
  },
  {
    id: 'editing.copy',
    name: 'Copiar',
    description: 'Copia la selección al portapapeles',
    category: 'Editing',
    context: 'global',
    risk: 'read',
    aliases: ['edicion.copiar'],
    defaultShortcuts: ['Ctrl+C'],
  },
  {
    id: 'editing.paste',
    name: 'Pegar',
    description: 'Pega desde el portapapeles',
    category: 'Editing',
    context: 'global',
    risk: 'write',
    aliases: ['edicion.pegar'],
    defaultShortcuts: ['Ctrl+V'],
  },
  {
    id: 'editing.delete',
    name: 'Eliminar',
    description: 'Elimina la selección',
    category: 'Editing',
    context: 'global',
    risk: 'dangerous',
    aliases: ['edicion.eliminar', 'clip.eliminar'],
    defaultShortcuts: ['Delete', 'Backspace'],
  },
  {
    id: 'editing.duplicate',
    name: 'Duplicar',
    description: 'Duplica la selección',
    category: 'Editing',
    context: 'global',
    risk: 'write',
    aliases: ['edicion.duplicar', 'clip.duplicar'],
    defaultShortcuts: ['Ctrl+D'],
  },
  {
    id: 'editing.selectAll',
    name: 'Seleccionar todo',
    description: 'Selecciona todos los clips',
    category: 'Selection',
    context: 'global',
    risk: 'write',
    aliases: ['edicion.seleccionarTodo'],
    defaultShortcuts: ['Ctrl+A'],
  },
  {
    id: 'editing.split',
    name: 'Dividir en playhead',
    description: 'Divide el clip seleccionado en el playhead',
    category: 'Editing',
    context: 'arrangement',
    risk: 'write',
    commandType: 'clip.split',
    aliases: ['clip.dividir'],
    defaultShortcuts: ['S'],
    intentionalShadowing: true,
  },

  // Track
  {
    id: 'track.create',
    name: 'Nueva pista de audio',
    description: 'Crea una pista de audio',
    category: 'Track',
    context: 'global',
    risk: 'write',
    commandType: 'track.create',
    aliases: ['pista.nueva', 'ui.agregarPista'],
    defaultShortcuts: ['Ctrl+Shift+A'],
  },
  {
    id: 'track.createMidi',
    name: 'Nueva pista MIDI',
    description: 'Crea una pista MIDI',
    category: 'Track',
    context: 'global',
    risk: 'write',
    commandType: 'track.create',
    aliases: ['pista.nuevaMidi'],
    defaultShortcuts: ['Ctrl+Shift+M'],
  },
  {
    id: 'track.delete',
    name: 'Eliminar pista',
    description: 'Elimina la pista seleccionada',
    category: 'Track',
    context: 'global',
    risk: 'dangerous',
    commandType: 'track.delete',
    aliases: ['pista.eliminarSeleccionada'],
    defaultShortcuts: ['Ctrl+Delete'],
  },
  {
    id: 'track.mute',
    name: 'Mute pista',
    description: 'Alterna mute de la pista seleccionada',
    category: 'Track',
    context: 'arrangement',
    risk: 'write',
    aliases: ['pista.mute'],
    defaultShortcuts: ['M'],
  },
  {
    id: 'track.solo',
    name: 'Solo pista',
    description: 'Alterna solo de la pista seleccionada',
    category: 'Track',
    context: 'arrangement',
    risk: 'write',
    aliases: ['pista.solo'],
    defaultShortcuts: ['Alt+S'],
  },
  {
    id: 'track.arm',
    name: 'Armar pista',
    description: 'Alterna armado de grabación',
    category: 'Track',
    context: 'arrangement',
    risk: 'write',
    aliases: ['pista.armar'],
    defaultShortcuts: ['Ctrl+Shift+R'],
  },
  {
    id: 'track.selectNext',
    name: 'Pista siguiente',
    description: 'Selecciona la siguiente pista',
    category: 'Navigation',
    context: 'arrangement',
    risk: 'write',
    aliases: ['pista.seleccionarSiguiente'],
    defaultShortcuts: ['Ctrl+Alt+ArrowDown', 'ArrowDown'],
  },
  {
    id: 'track.selectPrevious',
    name: 'Pista anterior',
    description: 'Selecciona la pista anterior',
    category: 'Navigation',
    context: 'arrangement',
    risk: 'write',
    aliases: ['pista.seleccionarAnterior'],
    defaultShortcuts: ['Ctrl+Alt+ArrowUp', 'ArrowUp'],
  },

  // Timeline / View
  {
    id: 'timeline.zoomIn',
    name: 'Acercar timeline',
    description: 'Zoom horizontal in',
    category: 'Timeline',
    context: 'global',
    risk: 'write',
    aliases: ['vista.zoomIn'],
    defaultShortcuts: ['Ctrl+Equal', 'Equal'],
  },
  {
    id: 'timeline.zoomOut',
    name: 'Alejar timeline',
    description: 'Zoom horizontal out',
    category: 'Timeline',
    context: 'global',
    risk: 'write',
    aliases: ['vista.zoomOut'],
    defaultShortcuts: ['Ctrl+Minus', 'Minus'],
  },
  {
    id: 'timeline.zoomToProject',
    name: 'Zoom a proyecto',
    description: 'Ajusta el zoom al proyecto completo',
    category: 'Timeline',
    context: 'global',
    risk: 'write',
    aliases: ['vista.zoomTodo'],
    defaultShortcuts: ['Ctrl+PageDown'],
  },
  {
    id: 'timeline.zoomToSelection',
    name: 'Zoom a selección',
    description: 'Ajusta el zoom a la selección',
    category: 'Timeline',
    context: 'arrangement',
    risk: 'write',
    aliases: ['vista.zoomSeleccion'],
    defaultShortcuts: ['Ctrl+PageUp'],
  },
  {
    id: 'timeline.scrollLeft',
    name: 'Desplazar izquierda',
    description: 'Desplaza la timeline a la izquierda',
    category: 'Navigation',
    context: 'arrangement',
    risk: 'write',
    aliases: ['vista.scrollIzquierda'],
    defaultShortcuts: ['Alt+ArrowLeft'],
  },
  {
    id: 'timeline.scrollRight',
    name: 'Desplazar derecha',
    description: 'Desplaza la timeline a la derecha',
    category: 'Navigation',
    context: 'arrangement',
    risk: 'write',
    aliases: ['vista.scrollDerecha'],
    defaultShortcuts: ['Alt+ArrowRight'],
  },

  // Tools
  {
    id: 'view.toolSelect',
    name: 'Herramienta seleccionar',
    description: 'Activa la herramienta de selección',
    category: 'View',
    context: 'arrangement',
    risk: 'write',
    commandType: 'ui.setTool',
    aliases: ['herramienta.select'],
    defaultShortcuts: ['1'],
  },
  {
    id: 'view.toolMove',
    name: 'Herramienta mover',
    description: 'Activa la herramienta de mover',
    category: 'View',
    context: 'arrangement',
    risk: 'write',
    aliases: ['herramienta.move'],
    defaultShortcuts: ['2'],
  },
  {
    id: 'view.toolPencil',
    name: 'Herramienta lápiz',
    description: 'Activa la herramienta lápiz',
    category: 'View',
    context: 'arrangement',
    risk: 'write',
    aliases: ['herramienta.pencil'],
    defaultShortcuts: ['3'],
  },
  {
    id: 'view.toolSplit',
    name: 'Herramienta tijeras',
    description: 'Activa la herramienta de dividir',
    category: 'View',
    context: 'arrangement',
    risk: 'write',
    aliases: ['herramienta.split'],
    defaultShortcuts: ['4'],
  },
  {
    id: 'view.toolEraser',
    name: 'Herramienta borrador',
    description: 'Activa la herramienta borrador',
    category: 'View',
    context: 'arrangement',
    risk: 'write',
    aliases: ['herramienta.eraser'],
    defaultShortcuts: ['5'],
  },

  {
    id: 'ai.askSelection',
    name: 'Preguntar a Jas sobre selección',
    description: 'Ancla notas MIDI o un fragmento de plan.md al chat (Ctrl+L)',
    category: 'AI',
    context: 'global',
    risk: 'read',
    aliases: ['ia.preguntarSeleccion', 'ventana.preguntarSeleccion'],
    defaultShortcuts: ['Ctrl+L'],
  },

  // Window
  {
    id: 'window.commandPalette',
    name: 'Paleta de comandos',
    description: 'Abre la paleta de comandos',
    category: 'Window',
    context: 'global',
    risk: 'read',
    aliases: ['ventana.paletaComandos'],
    defaultShortcuts: ['Ctrl+Shift+P'],
  },
  {
    id: 'window.keyboardShortcuts',
    name: 'Atajos de teclado',
    description: 'Abre la configuración de atajos',
    category: 'Window',
    context: 'global',
    risk: 'read',
    aliases: ['ventana.atajos'],
    defaultShortcuts: ['Ctrl+Shift+,'],
  },
  {
    id: 'window.midiMap',
    name: 'Control MIDI / MIDI Learn',
    description: 'Asigna notas, CC y teclas a comandos, mixer, sustain y plugins',
    category: 'MIDI',
    context: 'global',
    risk: 'write',
    aliases: ['ventana.midiMap', 'ventana.controlMidi'],
    defaultShortcuts: ['Ctrl+Shift+M'],
  },
  {
    id: 'window.terminal',
    name: 'Terminal',
    description: 'Abre la Terminal del DAW (CLI y ejecución de la IA)',
    category: 'Window',
    context: 'global',
    risk: 'read',
    aliases: ['ventana.terminal'],
    defaultShortcuts: ['Ctrl+`'],
  },
  {
    id: 'window.toggleLeft',
    name: 'Panel izquierdo',
    description: 'Muestra u oculta el panel izquierdo',
    category: 'Window',
    context: 'global',
    risk: 'write',
    aliases: ['ventana.barraLateral'],
    defaultShortcuts: ['Ctrl+B'],
  },
  {
    id: 'window.toggleBottom',
    name: 'Panel inferior',
    description: 'Muestra u oculta el panel inferior',
    category: 'Window',
    context: 'global',
    risk: 'write',
    aliases: ['ventana.panelInferior'],
    defaultShortcuts: ['Ctrl+J'],
  },
  {
    id: 'window.toggleRight',
    name: 'Panel derecho',
    description: 'Muestra u oculta el panel derecho',
    category: 'Window',
    context: 'global',
    risk: 'write',
    aliases: ['ventana.panelDerecho'],
    defaultShortcuts: ['Ctrl+Shift+J'],
  },
  {
    id: 'window.projectSettings',
    name: 'Ajustes del proyecto',
    description: 'Abre los ajustes del proyecto',
    category: 'Window',
    context: 'global',
    risk: 'read',
    aliases: ['ventana.ajustes'],
    defaultShortcuts: ['Ctrl+8'],
  },
];

export function getActionCatalog(): ActionDefinition[] {
  return ACTION_CATALOG.map((a) => ({ ...a }));
}
